version: '3.8'

volumes:
  postgres-data:
  rabbitmq-data:
  
networks:
  internal-network:

services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOSTNAME: postgresdb
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: internal-network

  db:
    container_name: postgresdb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:  

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres  

    network_mode: internal-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      # - "5672:5672"  # Expose RabbitMQ port for external access (if needed)
      - "15672:15672"  # Expose RabbitMQ management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      internal-network:
        aliases:
          - rabbitmq  # Alias for the RabbitMQ container